### ISSUE TITLE
Question about scene flow generation

### ISSUE THREAD

**Issue by f-sky** [princeton-vl/RAFT-3D#1]
I have a question about [here](https://github.com/princeton-vl/RAFT-3D/blob/master/raft3d/projective_ops.py#L65).
When we are generating scene flow using optical flow and depth maps, shouldn't we interpolate on depth1 using x1 and y1, and then backproject using interpolated depths?
Thank you!

**Comment by zachteed** [comment]
Hi, this function is using the `disparity_change` to compute 3D flow. In sceneflow.py

```
depth1 = torch.from_numpy(intrinsics[0] / disp1).float()
depth2 = torch.from_numpy(intrinsics[0] / disp2).float()

# transformed depth
depth12 = torch.from_numpy(intrinsics[0] / (disp1 + disparity_change)).float()

flow3d = pops.backproject_flow3d(flow2d, depth1, depth12, intrinsics)
```

depth12 is already represented in the coordinates of the first frame, so no interpolation is necessary.

**Comment by Bayrambai** [comment]
Hi,
how do you fine disparity_change in the above code snippet?
Thanks
