### ISSUE TITLE
Question about the train_kitti

### ISSUE THREAD

**Issue by MiaoMiaoMeng** [princeton-vl/RAFT-3D#6]
Hi，
Thanks for sharing the wonderful work.
I have some question about the 'train_kitti.py', I found 'kitti.py' in your project’s folder ‘data_readers’  is for submission the kitti datasets instead of training.  In train_kitti.py I can‘t found class KITTI, and in KITTIEval we can’t get object ‘flow_gt’ and ‘valid’ 
I try to code it by my self，so I add _‘flow_gt = flow_gt[self.crop:]’_ and _valid = flow_gt_ in kitty.py but I got some exception like that 
![image](https://user-images.githubusercontent.com/35400400/127972986-53bf4fc4-a127-410a-ac6e-0967c9393174.png)

Could you upload the KITTI and KITTIEval both？

By the way, the reason why I need to retrain the model is that I cannot get the expected results from your pre-trained model.
![image](https://user-images.githubusercontent.com/35400400/127979420-f26faa9a-6a73-4b5c-8e28-8ada517fd89f.png)

**Comment by MiaoMiaoMeng** [comment]
Okay, I think I found the problem. 
In raft.raft_bilaplacian, should we perform a log() operation on Ts and then return it?
Because if we don’t log() it to tensor，we will get an object of 'map' type.
And now I get the same result as the paper
![image](https://user-images.githubusercontent.com/35400400/128442762-4b6dd519-593a-4601-9c3e-12658a009286.png)

**Comment by zachteed** [comment]
Hi, I just posted the KITTI training / eval scripts so you should be able to finetune the models on the KITTI dataset now.

**Comment by BillyYuZJU** [comment]
@MiaoMiaoMeng Hi, I meet the same problem when try to run the demo. Could you elaborate on how to operate on Ts to get the same result as the paper?



> Hi， Thanks for sharing the wonderful work. I have some question about the 'train_kitti.py', I found 'kitti.py' in your project’s folder ‘data_readers’ is for submission the kitti datasets instead of training. In train_kitti.py I can‘t found class KITTI, and in KITTIEval we can’t get object ‘flow_gt’ and ‘valid’ I try to code it by my self，so I add _‘flow_gt = flow_gt[self.crop:]’_ and _valid = flow_gt_ in kitty.py but I got some exception like that ![image](https://user-images.githubusercontent.com/35400400/127972986-53bf4fc4-a127-410a-ac6e-0967c9393174.png)
> 
> Could you upload the KITTI and KITTIEval both？
> 
> By the way, the reason why I need to retrain the model is that I cannot get the expected results from your pre-trained model. ![image](https://user-images.githubusercontent.com/35400400/127979420-f26faa9a-6a73-4b5c-8e28-8ada517fd89f.png)
